### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by blakeembrey** [kevinbeaty/any-promise#18]
Hey! I've been using the project for a while with TypeScript and a custom type definition - would you be interested in merging a TypeScript definition the defines the module? For reference, here's my current implementation: https://github.com/typed-typings/npm-any-promise.

**Comment by kevinbeaty** [comment]
Sure.  I have yet to use TypeScript, but from what I understand, the definition would be maintained separately from the source code, correct? 

Would you be willing to help out with initial PR and occasional maintenance?  I really don't expect many changes to the interface over time, but there are a few upcoming, e.g. #14 and likely #15

**Comment by blakeembrey** [comment]
Yes, absolutely! See https://github.com/typings/typings/issues/322 for more info on what I've been trying to do too 😄

**Comment by kevinbeaty** [comment]
Awesome, thanks!

**Comment by kevinbeaty** [comment]
Published in v 1.3.0
