### ISSUE TITLE
if no native promise implementation found, try to require a bunch of promise libraries

### ISSUE THREAD

**Issue by jonathanong** [kevinbeaty/any-promise#5]
i wanna deprecate https://github.com/normalize/native-or-bluebird, but the problem with this library is that on node v0.10, you HAVE to configure your app. this would be a breaking change and HAVING to configure your app is not the ideal UX.

what do you think about try/catching a few libraries? if so, i'll deprecate `native-or-bluebird` and have everyone migrate to this module. of course, you'll only try/catch a few libraries if and only if a native implementation is not found. otherwise, end-developers will have to configure the promise implementation themselves to not use the native implementation

**Comment by kevinbeaty** [comment]
If I understand your question correctly, I think it does do what you are saying: https://github.com/kevinbeaty/any-promise/blob/master/register.js#L124

For Node.js <0.12, it will not load the global Promise, and try to auto-detect an implementation.  It will only throw if nothing can be detected.

**Comment by jonathanong** [comment]
oh shit it does do that. sorry, i can't read

**Comment by kevinbeaty** [comment]
Haha.  No problem :)
