### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by jonathanong** [kevinbeaty/any-promise#6]
can you publish v1?

**Comment by kevinbeaty** [comment]
Yup.  I almost made `0.2.0`.    Give me a few days to let the dust settle from #1 and your normalize/mz#16 .  If there are no major objections that lead to changes, I will publish `1.0.0`.

**Comment by jonathanong** [comment]
great :+1:

**Comment by kevinbeaty** [comment]
Eh.  The dust has settled enough.

Published 1.0.0

**Comment by RangerMauve** [comment]
The system works!
